repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8